### ISSUE TITLE
OpsManager Address Router

### ISSUE THREAD

**Issue by jasonm23** [opsmanager/book#1]
I'm starting a collection of articles on our git workflow in general, including (in no particular order)
- [x] Rebase and Squashing
- [ ] Rebase master / merge to master, pitfalls and tradeoffs 
- [ ] Git add with --patch
- [ ] Git color-words and other useful tidbits
- [ ] Story branch gem

Team Note: This list is to be modified by all, add any git workflow article titles you wish to see (or write.)

**Comment by rpbaltazar** [comment]
This issue was moved to opsmanager/opsmanager-wiki#5
