### ISSUE TITLE
Using mixins in view models

### ISSUE THREAD

**Issue by dominicwong617** [opsmanager/book#14]
In the [latest commit](https://github.com/opsmanager/OpsManager/commit/94ab42db53134cd269a0984f2bd6dfaa1e66b10c), the concept of view model mixins has been introduced. 

Let's say you have a view model called

``` coffeescript
class OPL.ViewModels.Shared.Reports.NewViewModel extends OPL.ViewModels.Base
```

and you have a mixin called OPL.ViewModels.Mixins.LocationsSelector

``` coffeescript
OPL.ViewModels.Mixins ||= {}
OPL.ViewModels.Mixins.LocationsSelector =
  methodOne: ->
    console.log "I am method one"
```

The way to use the mixin is to do declare the mixin in the view model

``` coffeescript
class OPL.ViewModels.Shared.Reports.NewViewModel extends OPL.ViewModels.Base
  mixins: [OPL.ViewModels.Mixins.LocationsSelector]

_.each OPL.ViewModels.Shared.Reports.NewViewModel.prototype.mixins, (mixin) ->
  _.extend OPL.ViewModels.Shared.Reports.NewViewModel.prototype, mixin
```

You can also declare the observable and observableArray values needed in the mixins. If you say,

``` coffeescript
OPL.ViewModels.Mixins ||= {}
OPL.ViewModels.Mixins.LocationsSelector = 
  observablesVariables: ["name", "gender"]
  observableArraysVariables: ["clothes", "cars"]

  methodOne: ->
    console.log "I am method one"
```

Then when you create a new `OPL.ViewModels.Shared.Reports.NewViewModel`, the instance will have `name` and `gender` as its observables and `clothes` and `cars` as its observableArrays.

The mixins are located in `opl/view_models/mixins` directory.

**Comment by rpbaltazar** [comment]
This issue was moved to opsmanager/opsmanager-wiki#10
