### ISSUE TITLE
itBehavesLikeRenderMainWithViewModel( "<factoryName>" )

### ISSUE THREAD

**Issue by wizztjh** [opsmanager/book#15]
We changed the itBehavesLikeRenderMainWithViewModel to include a factory name.
It will check if the factory spy is triggered now.

``` coffeescript
SharedExamples.AppLayout.itBehavesLikeRenderMainWithViewModel("createPersonnelUtilizationNewViewModel")
```

**Comment by rpbaltazar** [comment]
This issue was moved to opsmanager/opsmanager-wiki#11
