### ISSUE TITLE
Weak Map as DataModel Cache for DataStore - draft

### ISSUE THREAD

**Issue by wizztjh** [opsmanager/book#4]
If there are 2 view models in one view, 
View Model A and View Model B

if we update an attribute in View Model A and save, it will not be reflected in View Model B.
We can use jquery event for this, we can ask View Model A to listen to View Model B attribute changes event. But if there are more cases of event triggering and more types of event, it will be an entanglement of event triggers.

If we use weak map as data model cache, every view model will use the same data model object if they request the same record.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

``` coffeescript
cache = new WeakMap()

find: (id)->
  new Promise (reject, fulfil)->
    if cache.has(id)
      fulfil(cache.get(id))
    else
      @open().then (ds) ->
        ds.find(id).then (obj) ->
          dm = new DataModel(obj)
          cache.sets(dm)
          dm

ADA.datastore.DailyDrillingReport.find(11)
```

**Comment by rpbaltazar** [comment]
This issue was moved to opsmanager/opsmanager-wiki#7
